# Generated by Django 3.1.3 on 2020-11-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='url',
            new_name='file_path',
        ),
    ]
