# Generated by Django 3.1.3 on 2021-01-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_auto_20201215_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='board',
        ),
    ]
