# Generated by Django 3.1.3 on 2021-02-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_remove_card_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, to='kanban.Member'),
        ),
    ]
