# Generated by Django 3.1.3 on 2021-02-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_auto_20210206_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachment_type',
        ),
        migrations.DeleteModel(
            name='AttachmentType',
        ),
    ]
