# Generated by Django 3.1.3 on 2021-02-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_auto_20210206_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='position',
        ),
    ]
