# Generated by Django 3.1.3 on 2021-02-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_remove_board_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
