# Generated by Django 3.1.3 on 2021-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_auto_20210207_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='container',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
